### PR TITLE
sort the files of a folder before build hash

### PR DESCRIPTION
**Pull request by minhtuannguyen**

### CODE REVIEW

**Review by Harleqin — APPROVED** [review]
I'd like to have a test for this.  I guess that having the test shuffle the files in a directory before creation should result in `listFiles` also returning different orders.

**Review by Harleqin — COMMENTED** [review]
When would this have an effect?  Can we test this?

**Comment by minhtuannguyen** [comment]
I don't know exactly how to write a test reproducing this issue. It occurs only on different machine (on different operating systems).

**Comment by Harleqin** [comment]
Fixed in https://github.com/otto-de/lein-files-hash/commit/9b2f800aad2e446888afb7b3a15940e5f25ae224

**Pull request closed without merging**
